wsh_website:
    resource: "@WshWebsiteBundle/Controller/"
    type:     annotation
    prefix:   /

sonata_page_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /