<?php

namespace Wsh\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
    public function fetchPublishedClients($limit = null)
    {
        $dql = "SELECT c FROM Wsh\WebsiteBundle\Entity\Client c WHERE c.isPublished = true ORDER BY c.position";
        $query = $this->_em->createQuery($dql);
        if($limit !== null) {
            $query->setMaxResults($limit);
        }
        return $query->getResult();
    }

    public function fetchClientsCountries()
    {
        $dql = "SELECT DISTINCT c.country FROM Wsh\WebsiteBundle\Entity\Client c WHERE c.isPublished = true";
        $query = $this->_em->createQuery($dql);
        return $query->getResult();
    }
}
