<?php

namespace Wsh\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StaticHtmlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaticHtmlRepository extends EntityRepository
{
}
